/** 
 * @file
 * Defines all the PLD routes
 * @addtogroup core
 * @{
 * @addtogroup topo
 * @{
 * @addtogroup routes
 * Definition of all the routes
 * @{
 * Describe all the oriented routes.
 * Not to be included directly
 */
#include "topo.h"

 /** A3 to A4 - CERGY_LE_HAUT to MARNE_LA_VALLEE_CHESSY */
fb_index_t route_A3_A4[] = {
   CERGY_LE_HAUT,
   CERGY_ST_CHRISTOPHE,
   CERGY_PREFECTURE,
   NEUVILLE_UNIVERSITE,
   CONFLANT_FIN_DOISE,
   ACHERES_VILLE,
   MAISONS_LAFFITTE,
   SARTROUVILLE,
   HOUILLES_CARRIERE_SUR_SEINE,
   NANTERRE_PREFECTURE,
   LA_DEFENSE,
   CHARLES_DE_GAULLE_ETOILE,
   AUBER,
   CHATELET_LES_HALLES,
   GARE_DE_LYON,
   NATION,
   VINCENNES,
   VAL_DE_FONTENAY,
   NEUILLY_PLAISANCE,
   BRY_SUR_MARNE,
   NOISY_LE_GRAND_MONT_DEST,
   NOISY_CHAMPS,
   NOISIEL,
   LOGNES,
   TORCY,
   BUSSY_ST_GEORGES,
   VAL_DEUROPE,
   MARNE_LA_VALLEE_CHESSY,
};

/** A2 to A3 - BOISSY_SAINT_LEGER to SAINT_GERMAIN_EN_LAYE */
fb_index_t route_A3_A2[] = {
   CERGY_LE_HAUT,
   CERGY_ST_CHRISTOPHE,
   CERGY_PREFECTURE,
   NEUVILLE_UNIVERSITE,
   CONFLANT_FIN_DOISE,
   ACHERES_VILLE,
   MAISONS_LAFFITTE,
   SARTROUVILLE,
   HOUILLES_CARRIERE_SUR_SEINE,
   NANTERRE_PREFECTURE,
   LA_DEFENSE,
   CHARLES_DE_GAULLE_ETOILE,
   AUBER,
   CHATELET_LES_HALLES,
   GARE_DE_LYON,
   NATION,
   VINCENNES,
   FONTENAY_SOUS_BOIS,
   NOGENT_SUR_MARNE,
   JOINVILLE_LE_PONT,
   ST_MAUR_CRETEIL,
   LE_PARC_DE_ST_MAUR,
   CHAMPIGNY,
   LA_VARENNE_CHENNEVIERES,
   SUCY_BONNEUIL,
   BOISSY_SAINT_LEGER,
};

/** A5 to A4 - POISSY to MARNE_LA_VALLEE_CHESSY */
fb_index_t route_A5_A4[] = {
   POISSY,
   ACHERES_GRAND_CORMIER,
   MAISONS_LAFFITTE,
   SARTROUVILLE,
   HOUILLES_CARRIERE_SUR_SEINE,
   NANTERRE_PREFECTURE,
   LA_DEFENSE,
   CHARLES_DE_GAULLE_ETOILE,
   AUBER,
   CHATELET_LES_HALLES,
   GARE_DE_LYON,
   NATION,
   VINCENNES,
   VAL_DE_FONTENAY,
   NEUILLY_PLAISANCE,
   BRY_SUR_MARNE,
   NOISY_LE_GRAND_MONT_DEST,
   NOISY_CHAMPS,
   NOISIEL,
   LOGNES,
   TORCY,
   BUSSY_ST_GEORGES,
   VAL_DEUROPE,
   MARNE_LA_VALLEE_CHESSY,
};

/** A5 to A3 - POISSY to SAINT_GERMAIN_EN_LAYE */
fb_index_t route_A5_A2[] = {
   POISSY,
   ACHERES_GRAND_CORMIER,
   MAISONS_LAFFITTE,
   SARTROUVILLE,
   HOUILLES_CARRIERE_SUR_SEINE,
   NANTERRE_PREFECTURE,
   LA_DEFENSE,
   CHARLES_DE_GAULLE_ETOILE,
   AUBER,
   CHATELET_LES_HALLES,
   GARE_DE_LYON,
   NATION,
   VINCENNES,
   FONTENAY_SOUS_BOIS,
   NOGENT_SUR_MARNE,
   JOINVILLE_LE_PONT,
   ST_MAUR_CRETEIL,
   LE_PARC_DE_ST_MAUR,
   CHAMPIGNY,
   LA_VARENNE_CHENNEVIERES,
   SUCY_BONNEUIL,
   BOISSY_SAINT_LEGER,
};

/** A1 to A4 - SAINT_GERMAIN_EN_LAYE to MARNE_LA_VALLEE_CHESSY */
fb_index_t route_A1_A4[] = {
   SAINT_GERMAIN_EN_LAYE,
   LE_VESINET_LE_PECQ,
   LE_VESINET_CENTRE,
   CHATOU_CROISSY,
   RUEIL_MALMAISON,
   NANTERRE_VILLE,
   NANTERRE_UNIVERSITE,
   NANTERRE_PREFECTURE,
   LA_DEFENSE,
   CHARLES_DE_GAULLE_ETOILE,
   AUBER,
   CHATELET_LES_HALLES,
   GARE_DE_LYON,
   NATION,
   VINCENNES,
   VAL_DE_FONTENAY,
   NEUILLY_PLAISANCE,
   BRY_SUR_MARNE,
   NOISY_LE_GRAND_MONT_DEST,
   NOISY_CHAMPS,
   NOISIEL,
   LOGNES,
   TORCY,
   BUSSY_ST_GEORGES,
   VAL_DEUROPE,
   MARNE_LA_VALLEE_CHESSY,
};

/** A1 to A2 / SAINT_GERMAIN_EN_LAYE to BOISSY_SAINT_LEGER */
fb_index_t route_A1_A2[] = {
   SAINT_GERMAIN_EN_LAYE,
   LE_VESINET_LE_PECQ,
   LE_VESINET_CENTRE,
   CHATOU_CROISSY,
   RUEIL_MALMAISON,
   NANTERRE_VILLE,
   NANTERRE_UNIVERSITE,
   NANTERRE_PREFECTURE,
   LA_DEFENSE,
   CHARLES_DE_GAULLE_ETOILE,
   AUBER,
   CHATELET_LES_HALLES,
   GARE_DE_LYON,
   NATION,
   VINCENNES,
   FONTENAY_SOUS_BOIS,
   NOGENT_SUR_MARNE,
   JOINVILLE_LE_PONT,
   ST_MAUR_CRETEIL,
   LE_PARC_DE_ST_MAUR,
   CHAMPIGNY,
   LA_VARENNE_CHENNEVIERES,
   SUCY_BONNEUIL,
   BOISSY_SAINT_LEGER,
};

/**@}*/
/**@}*/
/**@}*/